import type { ComposeLayoutPresetDefinition } from './types.js';

function layoutSpecText(signature: string, rows: string[]): string {
    return [signature, ...rows].join('\n');
}

const MMA_M8N8K4_A_ROW_MAJOR_F16_TEXT = layoutSpecText('MMA_m8n8k4_A_row_major_f16: [T,R] -> [M,K]', [
    'T: [[1,0],[2,0],[0,0],[0,0],[4,0]]',
    'R: [[0,1],[0,2]]',
]);
const MMA_M8N8K4_A_COL_MAJOR_F16_TEXT = layoutSpecText('MMA_m8n8k4_A_col_major_f16: [T,R] -> [M,K]', [
    'T: [[0,1],[0,2],[0,0],[0,0],[4,0]]',
    'R: [[1,0],[2,0]]',
]);
const MMA_M8N8K4_B_ROW_MAJOR_F16_TEXT = layoutSpecText('MMA_m8n8k4_B_row_major_f16: [T,R] -> [K,N]', [
    'T: [[1,0],[2,0],[0,0],[0,0],[0,4]]',
    'R: [[0,1],[0,2]]',
]);
const MMA_M8N8K4_B_COL_MAJOR_F16_TEXT = layoutSpecText('MMA_m8n8k4_B_col_major_f16: [T,R] -> [K,N]', [
    'T: [[0,1],[0,2],[0,0],[0,0],[0,4]]',
    'R: [[1,0],[2,0]]',
]);
const MMA_M8N8K4_C_F16_TEXT = layoutSpecText('MMA_m8n8k4_C_f16: [T,R] -> [M,N]', [
    'T: [[1,0],[2,0],[0,0],[0,0],[4,0]]',
    'R: [[0,1],[0,2],[0,4]]',
]);
const MMA_M8N8K4_D_F16_TEXT = layoutSpecText('MMA_m8n8k4_D_f16: [T,R] -> [M,N]', [
    'T: [[1,0],[2,0],[0,0],[0,0],[4,0]]',
    'R: [[0,1],[0,2],[0,4]]',
]);
const MMA_M8N8K4_C_F32_TEXT = layoutSpecText('MMA_m8n8k4_C_f32: [T,R] -> [M,N]', [
    'T: [[1,0],[0,2],[0,0],[0,0],[4,0]]',
    'R: [[0,1],[2,0],[0,4]]',
]);
const MMA_M8N8K4_D_F32_TEXT = layoutSpecText('MMA_m8n8k4_D_f32: [T,R] -> [M,N]', [
    'T: [[1,0],[0,2],[0,0],[0,0],[4,0]]',
    'R: [[0,1],[2,0],[0,4]]',
]);
const MMA_M8N8K4_A_F64_TEXT = layoutSpecText('MMA_m8n8k4_A_f64: [T,R] -> [M,K]', [
    'T: [[0,1],[0,2],[1,0],[2,0],[4,0]]',
    'R: []',
]);
const MMA_M8N8K4_B_F64_TEXT = layoutSpecText('MMA_m8n8k4_B_f64: [T,R] -> [K,N]', [
    'T: [[1,0],[2,0],[0,1],[0,2],[0,4]]',
    'R: []',
]);
const MMA_M8N8K4_C_F64_TEXT = layoutSpecText('MMA_m8n8k4_C_f64: [T,R] -> [M,N]', [
    'T: [[0,2],[0,4],[1,0],[2,0],[4,0]]',
    'R: [[0,1]]',
]);
const MMA_M8N8K4_D_F64_TEXT = layoutSpecText('MMA_m8n8k4_D_f64: [T,R] -> [M,N]', [
    'T: [[0,2],[0,4],[1,0],[2,0],[4,0]]',
    'R: [[0,1]]',
]);
const MMA_M8N8K16_A_B8_TEXT = layoutSpecText('MMA_m8n8k16_A_b8: [T,R] -> [M,K]', [
    'T: [[0,4],[0,8],[1,0],[2,0],[0,0]]',
    'R: [[0,1],[0,2]]',
]);
const MMA_M8N8K16_B_B8_TEXT = layoutSpecText('MMA_m8n8k16_B_b8: [T,R] -> [N,K]', [
    'T: [[0,4],[0,8],[1,0],[2,0],[0,0]]',
    'R: [[1,0],[8,0]]',
]);
const MMA_M8N8K16_C_S32_TEXT = layoutSpecText('MMA_m8n8k16_C_s32: [T,R] -> [M,N]', [
    'T: [[1,0],[2,0],[0,1],[0,2],[0,0]]',
    'R: [[4,0]]',
]);
const MMA_M8N8K16_D_S32_TEXT = layoutSpecText('MMA_m8n8k16_D_s32: [T,R] -> [M,N]', [
    'T: [[1,0],[2,0],[0,1],[0,2],[0,0]]',
    'R: [[4,0]]',
]);

export const MMA_PRESET_DEFINITIONS = [
    {
        title: 'MMA_m8n8k4_A_row_major_f16',
        gpuArch: 'sm_70',
        instruction: 'mma',
        matrixSize: 'm8n8k4',
        dtype: 'f16',
        operand: 'A-row-major',
        specsText: MMA_M8N8K4_A_ROW_MAJOR_F16_TEXT,
        inputName: 'Hardware Layout',
    },
    {
        title: 'MMA_m8n8k4_A_col_major_f16',
        gpuArch: 'sm_70',
        instruction: 'mma',
        matrixSize: 'm8n8k4',
        dtype: 'f16',
        operand: 'A-col-major',
        specsText: MMA_M8N8K4_A_COL_MAJOR_F16_TEXT,
        inputName: 'Hardware Layout',
    },
    {
        title: 'MMA_m8n8k4_B_row_major_f16',
        gpuArch: 'sm_70',
        instruction: 'mma',
        matrixSize: 'm8n8k4',
        dtype: 'f16',
        operand: 'B-row-major',
        specsText: MMA_M8N8K4_B_ROW_MAJOR_F16_TEXT,
        inputName: 'Hardware Layout',
    },
    {
        title: 'MMA_m8n8k4_B_col_major_f16',
        gpuArch: 'sm_70',
        instruction: 'mma',
        matrixSize: 'm8n8k4',
        dtype: 'f16',
        operand: 'B-col-major',
        specsText: MMA_M8N8K4_B_COL_MAJOR_F16_TEXT,
        inputName: 'Hardware Layout',
    },
    {
        title: 'MMA_m8n8k4_C_f16',
        gpuArch: 'sm_70',
        instruction: 'mma',
        matrixSize: 'm8n8k4',
        dtype: 'f16',
        operand: 'C',
        specsText: MMA_M8N8K4_C_F16_TEXT,
        inputName: 'Hardware Layout',
    },
    {
        title: 'MMA_m8n8k4_D_f16',
        gpuArch: 'sm_70',
        instruction: 'mma',
        matrixSize: 'm8n8k4',
        dtype: 'f16',
        operand: 'D',
        specsText: MMA_M8N8K4_D_F16_TEXT,
        inputName: 'Hardware Layout',
    },
    {
        title: 'MMA_m8n8k4_C_f32',
        gpuArch: 'sm_70',
        instruction: 'mma',
        matrixSize: 'm8n8k4',
        dtype: 'f32',
        operand: 'C',
        specsText: MMA_M8N8K4_C_F32_TEXT,
        inputName: 'Hardware Layout',
    },
    {
        title: 'MMA_m8n8k4_D_f32',
        gpuArch: 'sm_70',
        instruction: 'mma',
        matrixSize: 'm8n8k4',
        dtype: 'f32',
        operand: 'D',
        specsText: MMA_M8N8K4_D_F32_TEXT,
        inputName: 'Hardware Layout',
    },
    {
        title: 'MMA_m8n8k4_A_f64',
        gpuArch: 'sm_70',
        instruction: 'mma',
        matrixSize: 'm8n8k4',
        dtype: 'f64',
        operand: 'A',
        specsText: MMA_M8N8K4_A_F64_TEXT,
        inputName: 'Hardware Layout',
    },
    {
        title: 'MMA_m8n8k4_B_f64',
        gpuArch: 'sm_70',
        instruction: 'mma',
        matrixSize: 'm8n8k4',
        dtype: 'f64',
        operand: 'B',
        specsText: MMA_M8N8K4_B_F64_TEXT,
        inputName: 'Hardware Layout',
    },
    {
        title: 'MMA_m8n8k4_C_f64',
        gpuArch: 'sm_70',
        instruction: 'mma',
        matrixSize: 'm8n8k4',
        dtype: 'f64',
        operand: 'C',
        specsText: MMA_M8N8K4_C_F64_TEXT,
        inputName: 'Hardware Layout',
    },
    {
        title: 'MMA_m8n8k4_D_f64',
        gpuArch: 'sm_70',
        instruction: 'mma',
        matrixSize: 'm8n8k4',
        dtype: 'f64',
        operand: 'D',
        specsText: MMA_M8N8K4_D_F64_TEXT,
        inputName: 'Hardware Layout',
    },
    {
        title: 'MMA_m8n8k16_A_b8',
        gpuArch: 'sm_75',
        instruction: 'mma',
        matrixSize: 'm8n8k16',
        dtype: 'b8',
        operand: 'A',
        comments: ['b8 represents 8-bit elements (u8/s8).'],
        specsText: MMA_M8N8K16_A_B8_TEXT,
        inputName: 'Hardware Layout',
    },
    {
        title: 'MMA_m8n8k16_B_b8',
        gpuArch: 'sm_75',
        instruction: 'mma',
        matrixSize: 'm8n8k16',
        dtype: 'b8',
        operand: 'B',
        comments: ['b8 represents 8-bit elements (u8/s8).'],
        specsText: MMA_M8N8K16_B_B8_TEXT,
        inputName: 'Hardware Layout',
    },
    {
        title: 'MMA_m8n8k16_C_s32',
        gpuArch: 'sm_75',
        instruction: 'mma',
        matrixSize: 'm8n8k16',
        dtype: 's32',
        operand: 'C',
        specsText: MMA_M8N8K16_C_S32_TEXT,
        inputName: 'Hardware Layout',
    },
    {
        title: 'MMA_m8n8k16_D_s32',
        gpuArch: 'sm_75',
        instruction: 'mma',
        matrixSize: 'm8n8k16',
        dtype: 's32',
        operand: 'D',
        specsText: MMA_M8N8K16_D_S32_TEXT,
        inputName: 'Hardware Layout',
    },
    {
        name: 'MMA_m8n8k32_A_b4',
        gpuArch: 'sm_75',
        instruction: 'mma',
        matrixSize: 'm8n8k32',
        dtype: 'b4',
        operand: 'A',
        comments: ['b4 represents 4-bit elements (u4/s4).'],
        signature: '[T,R] -> [M,K]',
        rows: [['T', '[[0,8],[0,16],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[0,2],[0,4]]']],
    },
    {
        name: 'MMA_m8n8k32_B_b4',
        gpuArch: 'sm_75',
        instruction: 'mma',
        matrixSize: 'm8n8k32',
        dtype: 'b4',
        operand: 'B',
        comments: ['b4 represents 4-bit elements (u4/s4).'],
        signature: '[T,R] -> [K,N]',
        rows: [['T', '[[8,0],[16,0],[0,1],[0,2],[0,4]]'], ['R', '[[1,0],[2,0],[4,0]]']],
    },
    {
        name: 'MMA_m8n8k32_C_s32',
        gpuArch: 'sm_75',
        instruction: 'mma',
        matrixSize: 'm8n8k32',
        dtype: 's32',
        operand: 'C',
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1]]']],
    },
    {
        name: 'MMA_m8n8k32_D_s32',
        gpuArch: 'sm_75',
        instruction: 'mma',
        matrixSize: 'm8n8k32',
        dtype: 's32',
        operand: 'D',
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1]]']],
    },
    {
        name: 'MMA_m8n8k128_A_b1',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm8n8k128',
        dtype: 'b1',
        operand: 'A',
        signature: '[T,R] -> [M,K]',
        rows: [['T', '[[0,32],[0,64],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[0,2],[0,4],[0,8],[0,16]]']],
    },
    {
        name: 'MMA_m8n8k128_B_b1',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm8n8k128',
        dtype: 'b1',
        operand: 'B',
        signature: '[T,R] -> [K,N]',
        rows: [['T', '[[32,0],[64,0],[0,1],[0,2],[0,4]]'], ['R', '[[1,0],[2,0],[4,0],[8,0],[16,0]]']],
    },
    {
        name: 'MMA_m8n8k128_C_s32',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm8n8k128',
        dtype: 's32',
        operand: 'C',
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1]]']],
    },
    {
        name: 'MMA_m8n8k128_D_s32',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm8n8k128',
        dtype: 's32',
        operand: 'D',
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1]]']],
    },
    {
        name: 'MMA_m16n8k4_A_tf32',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k4',
        dtype: 'tf32',
        operand: 'A',
        signature: '[T,R] -> [M,K]',
        rows: [['T', '[[0,1],[0,2],[1,0],[2,0],[4,0]]'], ['R', '[[8,0]]']],
    },
    {
        name: 'MMA_m16n8k4_A_f64',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k4',
        dtype: 'f64',
        operand: 'A',
        signature: '[T,R] -> [M,K]',
        rows: [['T', '[[0,1],[0,2],[1,0],[2,0],[4,0]]'], ['R', '[[8,0]]']],
    },
    {
        name: 'MMA_m16n8k4_B_tf32',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k4',
        dtype: 'tf32',
        operand: 'B',
        signature: '[T] -> [K,N]',
        rows: [['T', '[[1,0],[2,0],[0,1],[0,2],[0,4]]']],
    },
    {
        name: 'MMA_m16n8k4_B_f64',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k4',
        dtype: 'f64',
        operand: 'B',
        signature: '[T] -> [K,N]',
        rows: [['T', '[[1,0],[2,0],[0,1],[0,2],[0,4]]']],
    },
    {
        name: 'MMA_m16n8k4_C_f32',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k4',
        dtype: 'f32',
        operand: 'C',
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k4_D_f32',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k4',
        dtype: 'f32',
        operand: 'D',
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k4_C_f64',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k4',
        dtype: 'f64',
        operand: 'C',
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k4_D_f64',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k4',
        dtype: 'f64',
        operand: 'D',
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k8_A_b16',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k8',
        dtype: 'b16',
        operand: 'A',
        comments: ['b16 represents 16-bit elements (f16/bf16).'],
        signature: '[T,R] -> [M,K]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k8_A_tf32',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k8',
        dtype: 'tf32',
        operand: 'A',
        signature: '[T,R] -> [M,K]',
        rows: [['T', '[[0,1],[0,2],[1,0],[2,0],[4,0]]'], ['R', '[[8,0],[0,4]]']],
    },
    {
        name: 'MMA_m16n8k8_A_f64',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k8',
        dtype: 'f64',
        operand: 'A',
        signature: '[T,R] -> [M,K]',
        rows: [['T', '[[0,1],[0,2],[1,0],[2,0],[4,0]]'], ['R', '[[8,0],[0,4]]']],
    },
    {
        name: 'MMA_m16n8k8_B_b16',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k8',
        dtype: 'b16',
        operand: 'B',
        comments: ['b16 represents 16-bit elements (f16/bf16).'],
        signature: '[T,R] -> [K,N]',
        rows: [['T', '[[2,0],[4,0],[0,1],[0,2],[0,4]]'], ['R', '[[1,0]]']],
    },
    {
        name: 'MMA_m16n8k8_B_tf32',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k8',
        dtype: 'tf32',
        operand: 'B',
        signature: '[T,R] -> [K,N]',
        rows: [['T', '[[1,0],[2,0],[0,1],[0,2],[0,4]]'], ['R', '[[4,0]]']],
    },
    {
        name: 'MMA_m16n8k8_B_f64',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k8',
        dtype: 'f64',
        operand: 'B',
        signature: '[T,R] -> [K,N]',
        rows: [['T', '[[1,0],[2,0],[0,1],[0,2],[0,4]]'], ['R', '[[4,0]]']],
    },
    {
        name: 'MMA_m16n8k8_C_b16',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k8',
        dtype: 'b16',
        operand: 'C',
        comments: ['b16 represents 16-bit elements (f16/bf16).'],
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k8_D_b16',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k8',
        dtype: 'b16',
        operand: 'D',
        comments: ['b16 represents 16-bit elements (f16/bf16).'],
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k8_C_b32',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k8',
        dtype: 'b32',
        operand: 'C',
        comments: ['b32 represents 32-bit elements (f32/tf32).'],
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k8_D_b32',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k8',
        dtype: 'b32',
        operand: 'D',
        comments: ['b32 represents 32-bit elements (f32/tf32).'],
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k8_C_f64',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k8',
        dtype: 'f64',
        operand: 'C',
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k8_D_f64',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k8',
        dtype: 'f64',
        operand: 'D',
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k16_A_b16',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k16',
        dtype: 'b16',
        operand: 'A',
        comments: ['b16 represents 16-bit elements (f16/bf16).'],
        signature: '[T,R] -> [M,K]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0],[0,8]]']],
    },
    {
        name: 'MMA_m16n8k16_A_f64',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k16',
        dtype: 'f64',
        operand: 'A',
        signature: '[T,R] -> [M,K]',
        rows: [['T', '[[0,1],[0,2],[1,0],[2,0],[4,0]]'], ['R', '[[8,0],[0,4],[0,8]]']],
    },
    {
        name: 'MMA_m16n8k16_A_b8',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k16',
        dtype: 'b8',
        operand: 'A',
        comments: ['b8 represents 8-bit elements (u8/s8/e4m3/e5m2).'],
        signature: '[T,R] -> [M,K]',
        rows: [['T', '[[0,4],[0,8],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[0,2],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k16_B_b16',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k16',
        dtype: 'b16',
        operand: 'B',
        comments: ['b16 represents 16-bit elements (f16/bf16).'],
        signature: '[T,R] -> [K,N]',
        rows: [['T', '[[2,0],[4,0],[0,1],[0,2],[0,4]]'], ['R', '[[1,0],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k16_B_f64',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k16',
        dtype: 'f64',
        operand: 'B',
        signature: '[T,R] -> [K,N]',
        rows: [['T', '[[1,0],[2,0],[0,1],[0,2],[0,4]]'], ['R', '[[4,0],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k16_B_b8',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k16',
        dtype: 'b8',
        operand: 'B',
        comments: ['b8 represents 8-bit elements (u8/s8/e4m3/e5m2).'],
        signature: '[T,R] -> [K,N]',
        rows: [['T', '[[4,0],[8,0],[0,1],[0,2],[0,4]]'], ['R', '[[1,0],[2,0]]']],
    },
    {
        name: 'MMA_m16n8k16_C_f16',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k16',
        dtype: 'f16',
        operand: 'C',
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k16_D_f16',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k16',
        dtype: 'f16',
        operand: 'D',
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k16_C_b32',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k16',
        dtype: 'b32',
        operand: 'C',
        comments: ['b32 represents 32-bit elements (f32/s32).'],
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k16_D_b32',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k16',
        dtype: 'b32',
        operand: 'D',
        comments: ['b32 represents 32-bit elements (f32/s32).'],
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k16_C_f64',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k16',
        dtype: 'f64',
        operand: 'C',
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k16_D_f64',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k16',
        dtype: 'f64',
        operand: 'D',
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k32_A_b4',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k32',
        dtype: 'b4',
        operand: 'A',
        comments: ['b4 represents 4-bit elements (u4/s4/e2m1).'],
        signature: '[T,R] -> [M,K]',
        rows: [['T', '[[0,8],[0,16],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[0,2],[0,4],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k32_A_b8',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k32',
        dtype: 'b8',
        operand: 'A',
        comments: ['b8 represents 8-bit elements (u8/s8/e4m3/e5m2/e3m2/e2m3).'],
        signature: '[T,R] -> [M,K]',
        rows: [['T', '[[0,4],[0,8],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[0,2],[8,0],[0,16]]']],
    },
    {
        name: 'MMA_m16n8k32_B_b4',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k32',
        dtype: 'b4',
        operand: 'B',
        comments: ['b4 represents 4-bit elements (u4/s4/e2m1).'],
        signature: '[T,R] -> [K,N]',
        rows: [['T', '[[8,0],[16,0],[0,1],[0,2],[0,4]]'], ['R', '[[1,0],[2,0],[4,0]]']],
    },
    {
        name: 'MMA_m16n8k32_B_b8',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k32',
        dtype: 'b8',
        operand: 'B',
        comments: ['b8 represents 8-bit elements (u8/s8/e4m3/e5m2/e3m2/e2m3).'],
        signature: '[T,R] -> [K,N]',
        rows: [['T', '[[4,0],[8,0],[0,1],[0,2],[0,4]]'], ['R', '[[1,0],[2,0],[16,0]]']],
    },
    {
        name: 'MMA_m16n8k32_C_f16',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k32',
        dtype: 'f16',
        operand: 'C',
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k32_D_f16',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k32',
        dtype: 'f16',
        operand: 'D',
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k32_C_b32',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k32',
        dtype: 'b32',
        operand: 'C',
        comments: ['b32 represents 32-bit elements (f32/s32).'],
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k32_D_b32',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k32',
        dtype: 'b32',
        operand: 'D',
        comments: ['b32 represents 32-bit elements (f32/s32).'],
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k64_A_b4',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k64',
        dtype: 'b4',
        operand: 'A',
        comments: ['b4 represents 4-bit elements (u4/s4/e2m1).'],
        signature: '[T,R] -> [M,K]',
        rows: [['T', '[[0,8],[0,16],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[0,2],[0,4],[8,0],[0,32]]']],
    },
    {
        name: 'MMA_m16n8k64_B_b4',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k64',
        dtype: 'b4',
        operand: 'B',
        comments: ['b4 represents 4-bit elements (u4/s4/e2m1).'],
        signature: '[T,R] -> [K,N]',
        rows: [['T', '[[8,0],[16,0],[0,1],[0,2],[0,4]]'], ['R', '[[1,0],[2,0],[4,0],[32,0]]']],
    },
    {
        name: 'MMA_m16n8k64_C_b32',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k64',
        dtype: 'b32',
        operand: 'C',
        comments: ['b32 represents 32-bit elements (f32/s32).'],
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k64_D_b32',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k64',
        dtype: 'b32',
        operand: 'D',
        comments: ['b32 represents 32-bit elements (f32/s32).'],
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k128_A_b1',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k128',
        dtype: 'b1',
        operand: 'A',
        signature: '[T,R] -> [M,K]',
        rows: [['T', '[[0,32],[0,64],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[0,2],[0,4],[0,8],[0,16],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k128_B_b1',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k128',
        dtype: 'b1',
        operand: 'B',
        signature: '[T,R] -> [K,N]',
        rows: [['T', '[[32,0],[64,0],[0,1],[0,2],[0,4]]'], ['R', '[[1,0],[2,0],[4,0],[8,0],[16,0]]']],
    },
    {
        name: 'MMA_m16n8k128_C_s32',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k128',
        dtype: 's32',
        operand: 'C',
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k128_D_s32',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k128',
        dtype: 's32',
        operand: 'D',
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k256_B_b1',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k256',
        dtype: 'b1',
        operand: 'B',
        signature: '[T,R] -> [K,N]',
        rows: [['T', '[[32,0],[64,0],[0,1],[0,2],[0,4]]'], ['R', '[[1,0],[2,0],[4,0],[8,0],[16,0],[128,0]]']],
    },
    {
        name: 'MMA_m16n8k256_C_s32',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k256',
        dtype: 's32',
        operand: 'C',
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k256_D_s32',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k256',
        dtype: 's32',
        operand: 'D',
        signature: '[T,R] -> [M,N]',
        rows: [['T', '[[0,2],[0,4],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[8,0]]']],
    },
    {
        name: 'MMA_m16n8k256_A_b1',
        gpuArch: 'sm_80',
        instruction: 'mma',
        matrixSize: 'm16n8k256',
        dtype: 'b1',
        operand: 'A',
        signature: '[T,R] -> [M,K]',
        rows: [['T', '[[0,32],[0,64],[1,0],[2,0],[4,0]]'], ['R', '[[0,1],[0,2],[0,4],[0,8],[0,16],[8,0],[0,128]]']],
    },
] satisfies ComposeLayoutPresetDefinition[];
